import { DM_Sans } from 'next/font/google'
import "/public/assets/css/style.css"
import "/public/assets/css/responsive.css"

const dm = DM_Sans({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin'],
    variable: "--dm",
    display: 'swap',
})
export const metadata = {
    title: 'PM IT Solution',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${dm.variable} body header-fixed`}>{children}</body>
        </html>
    )
}
